name: revolution1401
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Common
  device_info_plus: ^8.0.0
  easy_localization: ^3.0.1
  go_router: ^6.0.1
  provider: ^6.0.5
  logger: ^1.1.0
  # otp_autofill: ^2.1.0
  url_launcher: ^6.1.7
  jwt_decoder: ^2.0.1
  flutter_cache_manager: ^3.3.0
  sentry_flutter: ^6.18.2
  after_layout: ^1.2.0
  # UI / Component
  bot_toast: ^4.0.3
  pinput: ^2.2.21
  flutter_svg: ^1.1.6
  shimmer: ^2.0.0
  percent_indicator: ^4.2.2
  flutter_blurhash: ^0.7.0 
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  separated_row: ^2.0.0
  separated_column: ^2.0.0
  glass_kit: ^2.0.1
  measured_size: ^1.0.0
  custom_pop_up_menu: ^1.2.4
  sticky_headers: ^0.3.0+2
  palette_generator: ^0.3.3+2
  flutter_rating_bar: ^4.0.1
  pull_to_refresh: ^2.0.0
  # Animations
  animated_text_kit: ^4.2.2
  dough: ^1.0.3
  flutter_staggered_animations: ^1.1.1
  flutter_animator: ^3.2.2
  searchbar_animation: ^0.0.4
  # Form
  flutter_form_builder: ^7.7.0
  form_builder_validators: ^8.4.0
  # NoSQL Database
  hive: ^2.2.3 
  hive_flutter: ^1.1.0
  # API
  retrofit: ^3.3.1
  dio: ^4.0.6 
  json_serializable: ^6.5.4
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  # Firebase
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  firebase_database: ^10.0.9
  # Utils
  # mobile_scanner: ^2.1.0
  share_plus: ^6.3.0
  flutter_html: ^3.0.0-alpha.5
  freezed_annotation: ^2.2.0
  connectivity_plus: ^3.0.2
  flutter_phoenix: ^1.1.0
  shamsi_date: ^1.0.1
  persian_datetime_picker: ^2.5.0
  # flutter_launcher_icons: ^0.11.0
  # flutter_app_name: ^0.1.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.8
  hive_generator: ^2.0.0
  retrofit_generator: ^4.2.0
  freezed: ^2.3.2

  # replace when this package update and bug fixed
  # flutter_launcher_icons:
  #   git:
  #     url: https://github.com/marcobazzani/flutter_launcher_icons.git
  #     ref: patch-1

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

flutter_app_name:
  name: "Revolution1401"

flutter:
  uses-material-design: true
  assets:
    - resources/langs/
    - assets/images/
    - assets/vectors/
    - assets/emojis/
    - assets/launcher/
  fonts:
    - family: yekanBakh
      fonts:
        - asset: resources/fonts/yekan-bakh/fa-en/yekan-bakh-fa-en-08-fat.ttf
          weight: 900
        - asset: resources/fonts/yekan-bakh/fa-en/yekan-bakh-fa-en-07-heavy.ttf
          weight: 800
        - asset: resources/fonts/yekan-bakh/fa-en/yekan-bakh-fa-en-06-bold.ttf
          weight: 700
        - asset: resources/fonts/yekan-bakh/fa-en/yekan-bakh-fa-en-05-medium.ttf
          weight: 600
        - asset: resources/fonts/yekan-bakh/fa-en/yekan-bakh-fa-en-04-regular.ttf
          weight: 500
        - asset: resources/fonts/yekan-bakh/fa-en/yekan-bakh-fa-en-03-light.ttf
          weight: 400
        - asset: resources/fonts/yekan-bakh/fa-en/yekan-bakh-fa-en-02-thin.ttf
          weight: 300
        - asset: resources/fonts/yekan-bakh/fa-en/yekan-bakh-fa-en-01-hairline.ttf
          weight: 200
        - asset: resources/fonts/yekan-bakh/fa-en/yekan-bakh-fa-en-01-hairline.ttf
          weight: 100
    - family: yekanBakhFaNum
      fonts:
        - asset: resources/fonts/yekan-bakh/fa-num/yekan-bakh-fa-num-08-fat.ttf
          weight: 900
        - asset: resources/fonts/yekan-bakh/fa-num/yekan-bakh-fa-num-07-heavy.ttf
          weight: 800
        - asset: resources/fonts/yekan-bakh/fa-num/yekan-bakh-fa-num-06-bold.ttf
          weight: 700
        - asset: resources/fonts/yekan-bakh/fa-num/yekan-bakh-fa-num-05-medium.ttf
          weight: 600
        - asset: resources/fonts/yekan-bakh/fa-num/yekan-bakh-fa-num-04-regular.ttf
          weight: 500
        - asset: resources/fonts/yekan-bakh/fa-num/yekan-bakh-fa-num-03-light.ttf
          weight: 400
        - asset: resources/fonts/yekan-bakh/fa-num/yekan-bakh-fa-num-02-thin.ttf
          weight: 300
        - asset: resources/fonts/yekan-bakh/fa-num/yekan-bakh-fa-num-01-hairline.ttf
          weight: 200
        - asset: resources/fonts/yekan-bakh/fa-num/yekan-bakh-fa-num-01-hairline.ttf
          weight: 100