// Generated by spider on 2022-07-09 12:08:41.645102

part of 'resources.dart';

class Images {
  Images._();

  static const String meydanAzadi = 'assets/images/meydan_azadi.jpg';
  static const String initialBackground = 'assets/images/initial.jpg';
}
