// Generated by spider on 2022-07-09 12:08:41.645102

part of 'resources.dart';

class Images {
  Images._();

  static const String meydanAzadi = 'assets/images/meydan_azadi.jpg';
  static const String initialBackground = 'assets/images/initial.jpg';
  static const String dena = 'assets/images/dena.jpg';
  static const String hosna = 'assets/images/hosna.jpg';
  static const String mahbobe = 'assets/images/mahbobe.jpg';
  static const String hadise = 'assets/images/hadise.jpg';
}
