// Generated by spider on 2022-07-09 12:08:41.786955

part of 'resources.dart';

class LauncherIcons {
  LauncherIcons._();

  static const String background = 'assets/launcher/background.png';
  static const String foreground = 'assets/launcher/foreground.png';
  static const String icon = 'assets/launcher/icon.png';
}
