// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcYxMnKT5OEqmsp9EU84DHaUuQGW5qiQI',
    appId: '1:435121144326:web:5d888cd5e3d8535fe0b987',
    messagingSenderId: '435121144326',
    projectId: 'paybuy-8adfa',
    authDomain: 'paybuy-8adfa.firebaseapp.com',
    storageBucket: 'paybuy-8adfa.appspot.com',
    measurementId: 'G-Y9Y2F8JLN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC91G90-iI_eJqRGN45N9D4o1kqDt5CNgI',
    appId: '1:12803684349:android:04cef9a4e061144ae0cb94',
    messagingSenderId: '12803684349',
    projectId: 'revolution-1401',
    storageBucket: 'revolution-1401.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy3IyQjWoJyeFnmkSN-fccmTPxQNK_6N8',
    appId: '1:435121144326:ios:a3f43400d15296c9e0b987',
    messagingSenderId: '435121144326',
    projectId: 'paybuy-8adfa',
    storageBucket: 'paybuy-8adfa.appspot.com',
    iosClientId: '435121144326-cu5de1l9jf80re815qc3uh7q0eugv0u3.apps.googleusercontent.com',
    iosBundleId: 'org.avapardaz.paybuy',
  );
}
